/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_position_free: (a: number, b: number) => void;
export const __wbg_get_position_row: (a: number) => number;
export const __wbg_set_position_row: (a: number, b: number) => void;
export const __wbg_get_position_column: (a: number) => number;
export const __wbg_set_position_column: (a: number, b: number) => void;
export const position_new: (a: number, b: number) => number;
export const position_debug_info: (a: number) => [number, number];
export const position_get_row: (a: number) => number;
export const position_get_column: (a: number) => number;
export const __wbg_pieceinfo_free: (a: number, b: number) => void;
export const __wbg_get_pieceinfo_piece: (a: number) => number;
export const __wbg_set_pieceinfo_piece: (a: number, b: number) => void;
export const __wbg_get_pieceinfo_player: (a: number) => number;
export const __wbg_set_pieceinfo_player: (a: number, b: number) => void;
export const __wbg_board_free: (a: number, b: number) => void;
export const board_new: () => number;
export const board_get_piece: (a: number, b: number) => number;
export const board_is_valid_move: (a: number, b: number, c: number) => number;
export const board_make_move: (a: number, b: number, c: number) => number;
export const board_make_move_with_promotion: (a: number, b: number, c: number, d: number) => number;
export const board_get_current_player: (a: number) => number;
export const board_get_valid_moves: (a: number, b: number) => [number, number];
export const board_get_valid_moves_by_coords: (a: number, b: number, c: number) => [number, number];
export const board_get_piece_by_coords: (a: number, b: number, c: number) => number;
export const board_make_move_by_coords: (a: number, b: number, c: number, d: number, e: number) => number;
export const board_make_move_by_coords_with_promotion: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const board_can_promote: (a: number, b: number, c: number, d: number, e: number) => number;
export const board_clone: (a: number) => number;
export const board_set_piece: (a: number, b: number, c: number, d: number) => number;
export const board_get_captured_piece_count: (a: number, b: number, c: number) => number;
export const board_add_captured_piece: (a: number, b: number, c: number) => void;
export const board_use_captured_piece: (a: number, b: number, c: number) => number;
export const board_can_drop_piece: (a: number, b: number, c: number, d: number) => number;
export const board_drop_piece: (a: number, b: number, c: number, d: number) => number;
export const hello_shogi: () => [number, number];
export const __wbindgen_export_0: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
